### ISSUE TITLE
[Design/UX] Splash Screen

### ISSUE THREAD

**Issue by emanuelconunaemme** [associazione-rousseau/camelot-flutter#32]
Screen showed for few seconds on startup. I think it should be white with rousseau in red or vice-versa. We need to create the Rousseau icon in different formats compatible with iOS and Android

**Comment by gedamial** [comment]
I would say red background with "Rousseau" in white (just like the propic of github's Associazione Rousseau account). And maybe with an animated loading icon.

**Comment by aledeniz** [comment]
I got the vectorial using the Trajan Pro 3 font, I am attaching a screenshot. 

![image](https://user-images.githubusercontent.com/439083/68522421-08df5400-02a3-11ea-9929-5a5057a0bc79.png)

Any preference about the red? The one in the screenshot is Pantone 172C.
The red of the trade mark is quite darker: https://euipo.europa.eu/eSearch/#details/trademarks/015480098

Also, what about the folder layout for the assets?

**Comment by aledeniz** [comment]
I sent a [PR](https://github.com/associazione-rousseau/camelot-flutter/pull/51) proposing a folder layout for the assets. I have also included the Adobe Illustrator artwork for the logo, in black letters on a white background, and a sample png.
To go further, I need the specific red, I could then produce a number of portrait and landsacape png files in red on white or white on red.

**Comment by marcodadamo** [comment]
Questa è una proposta di modifica della grafica, Logo centrale, in alto, Rousseau con sfondo rosso e logo M5S centrale.
### #52 [Design] Accesso Schermo.

**Comment by aledeniz** [comment]
@emanuelconunaemme wrote:
> can those be parametrized? I'm thinking about setting the color and the background. Otherwise, black is not super useful. We need white on red and red on white. Shall we just have the red and white sign with no background? In this way we can just use them with the desired background within a widget. This would be lighter.

As suggested in #51, we may have a number of options.

- First and foremost, we could use Natanael Gama's Cinzel instead of Adobe Trajan Pro 3. Cinzel is a great substitute for Trajan, but it is a bit lighter. Cinzel is an open source typeface, part of the [Google Font catalog](https://fonts.google.com/specimen/Cinzel). Thanks to the very liberal [Open Font License](https://github.com/google/fonts/tree/master/ofl/cinzel) we could embed the regular font in the mobile application (the regular font file is 54 kB), which would enable parameterization on the widgets through the TextStyle immutable class (e.g. see the [Flutter](https://flutter.dev/docs/cookbook/design/fonts) and the [TextStyle class](https://api.flutter.dev/flutter/painting/TextStyle-class.html) documentation).

- if switching to an open source typeface such as Cinzel is not an option, alternatively:

1. we could produce a svg and consume it though Daniel Field's [flutter_svg library](https://github.com/dnfield/flutter_svg).

2. we could try to use the CustomPaint/Canvas API route as in the [flutter logo](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/painting/flutter_logo.dart). It seems quite a lot of work.

3. we could produce smaller bitmaps (PNG8), perhaps only for the specific assets, not the entire screen. E.g. if the screen is 2208x1242 pixels, but the only asset is a text in the middle, we export the asset for screens, and then we use the widgets to align it squarely in the middle.

My vote is for Cinzel.

**Comment by aledeniz** [comment]
@emanuelconunaemme looking at @marcodadamo's screenshot proposal in #52, that could also be achieved either with a set of bitmap screenshots, either with a couple of bitmap (one each for the logos) and some dart, either with quite a lot of dart, either with a few svg, Dan Field's library, and some dart.
I'd personally start with a more minimalist approach (the Netflix like white text in the middle of a red background, using a Cinzel font for the text, all through dart), and then review at a later stage.

**Comment by emanuelconunaemme** [comment]
@aledeniz you PR was merged. I was wondering if it was something easy to do. At the end we only need white-no-background and black-no-background. The sizes have to fit the width of the screen for most devices. So, we can just import few static asset and make it super simple. We can compose it programmatically when we put it inside another widget.

**Comment by aledeniz** [comment]
@emanuelconunaemme I will create the static assets then. Adobe Illustrator has got a specific function (export for screens) that create all the appropriate screens, but it can extract only the set of asset for the specific screen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
